#!/usr/bin/env bash

tar -cvf app.tgz --exclude node_modules login
scp -i ../y -P 2222 app.tgz sam@localhost:/home/sam/local/app.tgz
ssh -p 2222 -i ../y sam@localhost -- "tar -C local -xvf /home/sam/local/app.tgz --exclude node_modules"



